"""init

Revision ID: 5109774501eb
Revises:
Create Date: 2026-03-12 20:53:34.018214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5109774501eb"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "has_desire",
            existing_type=postgresql.BIT(varying=True),
            type_=sa.Boolean(),
            existing_nullable=False,
            # manually added
            postgresql_using="has_desire::bit(1)::int::boolean",
        )
        batch_op.alter_column(
            "trusted",
            existing_type=postgresql.BIT(varying=True),
            type_=sa.Boolean(),
            existing_nullable=False,
            # manually added
            postgresql_using="trusted::bit(1)::int::boolean",
        )
        batch_op.alter_column("chat_id", existing_type=sa.BIGINT(), nullable=False)
        batch_op.create_unique_constraint(None, ["chat_id"])
        batch_op.create_unique_constraint(None, ["tg_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.alter_column("chat_id", existing_type=sa.BIGINT(), nullable=True)
        batch_op.alter_column(
            "trusted",
            existing_type=sa.Boolean(),
            type_=postgresql.BIT(varying=True),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "has_desire",
            existing_type=sa.Boolean(),
            type_=postgresql.BIT(varying=True),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
