"""remove chat_id

Revision ID: a44783274a95
Revises: 5109774501eb
Create Date: 2026-03-12 21:48:03.706075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a44783274a95"
down_revision: Union[str, Sequence[str], None] = "5109774501eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["tg_id"])
        batch_op.drop_column("chat_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("chat_id", sa.BIGINT(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
